name: freecad
channels:
- freecad
- conda-forge
dependencies:
- python
- freecad
- pre-commit=4.2.*
- mypy=1.16.*
- pytest==8.4.*
- pytest-cov==7.0.*
- pip:
  - -e . --config-settings editable_mode=strict # we use strict mode because of pylance
